# Generated by Django 4.2.17 on 2025-01-23 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=1024)),
                ('mediaPath', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1024)),
                ('mediaPath', models.FilePathField()),
                ('difficulty', models.CharField(choices=[('1', 'Easy'), ('2', 'Medium'), ('3', 'Difficult'), ('4', 'Hard')], max_length=1)),
                ('equipment', models.CharField(max_length=255)),
                ('bodyPartId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitApp.bodypart')),
                ('tags', models.ManyToManyField(to='fitApp.tags')),
            ],
        ),
    ]
